CREATE TABLE prize
(
    id             bigint generated by default as identity,
    name           varchar(25),
    description    varchar(100),
    value          varchar(25),
    stock          bigint NOT NULL DEFAULT '0',
    probability    decimal,
    categories     varchar(100)
)
